//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoVarejo
{
    using System;
    using System.Collections.Generic;
    
    public partial class produto_tb
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public produto_tb()
        {
            this.venda_tb = new HashSet<venda_tb>();
        }
    
        public int produto_id { get; set; }
        public string nome_prod { get; set; }
        public string descricao { get; set; }
        public Nullable<decimal> preco { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<venda_tb> venda_tb { get; set; }
    }
}
