//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoVarejo
{
    using System;
    using System.Collections.Generic;
    
    public partial class venda_tb
    {
        public int venda_id { get; set; }
        public Nullable<int> produto_id { get; set; }
        public Nullable<int> cliente_id { get; set; }
        public Nullable<int> funcionario_id { get; set; }
        public Nullable<System.DateTime> data { get; set; }
        public string forma_pagamento { get; set; }
        public string descricao { get; set; }
    
        public virtual cliente_tb cliente_tb { get; set; }
        public virtual funcionario_tb funcionario_tb { get; set; }
        public virtual produto_tb produto_tb { get; set; }
    }
}
